//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodsViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GodsViewer.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] _04_Level_1_dmp {
            get {
                object obj = ResourceManager.GetObject("_04_Level_1_dmp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Amiga_Level_1 {
            get {
                object obj = ResourceManager.GetObject("Amiga_Level_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Icon Gods {
            get {
                object obj = ResourceManager.GetObject("Gods", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static byte[] Gods_1991_Renegade_Disk_1_of_2_adf {
            get {
                object obj = ResourceManager.GetObject("Gods_1991_Renegade_Disk_1_of_2_adf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Gods_1991_Renegade_Disk_2_of_2_adf {
            get {
                object obj = ResourceManager.GetObject("Gods_1991_Renegade_Disk_2_of_2_adf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Gods_Disk_1_of_2_Track_00_filled_st {
            get {
                object obj = ResourceManager.GetObject("Gods_Disk_1_of_2_Track_00_filled_st", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Gods_Disk_2_of_2_st {
            get {
                object obj = ResourceManager.GetObject("Gods_Disk_2_of_2_st", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
